In [1]:
import pandas as pd
import seaborn as sns
import numpy as np

import json
import tweepy

import time
from tweepy import OAuthHandler
from tweepy import Stream

In [2]:
C_KEY = "5kCFmYbrCizZ2dpo3KD9dRfkl"
C_SECRET = "mNH0jlbgDcQQIThlIlrxkKWQLtle02hJh0aoM305wqQBR9nilb"
A_TOKEN_KEY = "1487949914185166848-eLF7W3icZwkg9dbdUr6swBMGCpFZQQ"
A_TOKEN_SECRET = "rIbMqldiv1ZbNe5gUAbNBwe19y1L28AxeCB2JBha8HgVV"
BEARER_TOKEN = "AAAAAAAAAAAAAAAAAAAAACLgggEAAAAAlM9KpqdlqBsMzwYtkPvPfhl2vrI%3DUhZEVr3Ho2jvmoRWLwQXTFStKVz1bAlU4f9rKOEsoQ4HUvwG9k"
auth = tweepy.OAuthHandler(C_KEY, C_SECRET)
auth.set_access_token(A_TOKEN_KEY, A_TOKEN_SECRET)
api = tweepy.API(auth)

In [3]:
class MyListener(Stream):
    
    def __init__(self, time_limit=30):
        self.start_time = time.time()
        self.limit = time_limit
        self.outFile = open('output.json', 'a')
        super(MyListener, self).__init__()
        
    def on_data(self, data):
        if (time.time() - self.start_time) < self.limit:
            self.outFile.write(data)
            self.outFile.write('\n')
            return True
        else:
            self.outFile.close()
            return False
    
    def on_error(self, status):
        print(status)

In [4]:
# stream = MyListener('5kCFmYbrCizZ2dpo3KD9dRfkl',
#                     'mNH0jlbgDcQQIThlIlrxkKWQLtle02hJh0aoM305wqQBR9nilb',
#                     '1487949914185166848-eLF7W3icZwkg9dbdUr6swBMGCpFZQQ',
#                     'rIbMqldiv1ZbNe5gUAbNBwe19y1L28AxeCB2JBha8HgVV')

In [5]:

# stream.filter(track='#FIFAWorldCup2022', time_limit=10)

## Problem 1

In [6]:
keyword = '#FIFAWorldCup2022'

posts = api.search_tweets(q=keyword, count=5000, )

In [7]:
with open('FIFAWorldCup2022.json', 'w') as out:
    for tweet in posts:
        json.dump(tweet._json, out)

## A)

In [8]:
with open('FIFAWorldCup2022_v2.json', 'w') as f2:
    for tweet in posts:
        f2.write(json.dumps(tweet._json, indent = 4))

In [9]:
# tweet = posts[0]._json
# for key, value in tweet.items():
#     print(key)

## B)

In [10]:
full_string = ''
for tweet in posts:
    full_string = full_string + tweet.user.location
    
full_string = full_string.split(",")
print(full_string)

['Timiaouine south الحسيمة いつかは🇰🇷へお嫁へㄱㄱ👰🏻\u200d♀️いつかは🇰🇷へお嫁へㄱㄱ👰🏻\u200d♀️いつかは🇰🇷へお嫁へㄱㄱ👰🏻\u200d♀️Istanbul Buenos AiresУкраинаValencia', ' EspañaMollet del Vallès', ' EspañaUp', ' India IndiaPUNADelhi東京都Mulfand acc#Qatar ماتوفيقي الا باللهTithanHyderabad', ' IndiaRachiEarthKolkata', ' Indiachennai IndiaTokyoLucca', ' Toscana - Tuscany - ItaPatnaBerlin', ' DeutschlandUPFès Médina', ' Royaume du Marocالرياض', ' المملكة العربية السعودالرياض', ' المملكة العربية السعودالرياض', ' المملكة العربية السعودالرياض', " المملكة العربية السعود대한민국mind somewhere BiharHong KongUkMassachusetts日本🇯🇵\u3000神奈川SpainN 13°48' 0'' / E 100°34' 0''Dhaka", ' BangladeshTokyoNYC']

### Most common countries appearing in place field for twitter posts with hashtag #FIFAWorldCup2022

In [11]:
from collections import defaultdict

countries = "Afghanistan, Albania, Algeria, Andorra, Angola, Antigua & Deps, Argentina, Armenia, Australia, Austria, Azerbaijan, Bahamas, Bahrain, Bangladesh, Barbados, Belarus, Belgium, Belize, Benin, Bhutan, Bolivia, Bosnia Herzegovina, Botswana, Brazil, Brunei, Bulgaria, Burkina, Burma, Burundi, Cambodia, Cameroon, Canada, Cape Verde, Central African Rep, Chad, Chile, China, Republic of China, Colombia, Comoros, Democratic Republic of the Congo, Republic of the Congo, Costa Rica, Croatia, Cuba, Cyprus, Czech Republic, Danzig, Denmark, Djibouti, Dominica, Dominican Republic, East Timor, Ecuador, Egypt, El Salvador, Equatorial Guinea, Eritrea, Estonia, Ethiopia, Fiji, Finland, France, Gabon, Gaza Strip, The Gambia, Georgia, Germany, Ghana, Greece, Grenada, Guatemala, Guinea, Guinea-Bissau, Guyana, Haiti, Holy Roman Empire, Honduras, Hungary, Iceland, India, Indonesia, Iran, Iraq, Republic of Ireland, Israel, Italy, Ivory Coast, Jamaica, Japan, Jonathanland, Jordan, Kazakhstan, Kenya, Kiribati, North Korea, South Korea, Kosovo, Kuwait, Kyrgyzstan, Laos, Latvia, Lebanon, Lesotho, Liberia, Libya, Liechtenstein, Lithuania, Luxembourg, Macedonia, Madagascar, Malawi, Malaysia, Maldives, Mali, Malta, Marshall Islands, Mauritania, Mauritius, Mexico, Micronesia, Moldova, Monaco, Mongolia, Montenegro, Morocco, Mount Athos, Mozambique, Namibia, Nauru, Nepal, Newfoundland, Netherlands, New Zealand, Nicaragua, Niger, Nigeria, Norway, Oman, Ottoman Empire, Pakistan, Palau, Panama, Papua New Guinea, Paraguay, Peru, Philippines, Poland, Portugal, Prussia, Qatar, Romania, Rome, Russian Federation, Rwanda, St Kitts & Nevis, St Lucia, Saint Vincent & the Grenadines, Samoa, San Marino, Sao Tome & Principe, Saudi Arabia, Senegal, Serbia, Seychelles, Sierra Leone, Singapore, Slovakia, Slovenia, Solomon Islands, Somalia, South Africa, Spain, Sri Lanka, Sudan, Suriname, Swaziland, Sweden, Switzerland, Syria, Tajikistan, Tanzania, Thailand, Togo, Tonga, Trinidad & Tobago, Tunisia, Turkey, Turkmenistan, Tuvalu, Uganda, Ukraine, United Arab Emirates, United Kingdom, United States, Uruguay, Uzbekistan, Vanuatu, Vatican City, Venezuela, Vietnam, Yemen, Zambia, Zimbabwe"
countries = countries.split(",")
countries = [c.strip() for c in countries]

country_dict = {key: 0 for key in countries}

for tweet in posts:  
    for c in countries:
            if c in tweet.user.location:
                country_dict[c] = country_dict[c] + 1

sorted_countries = sorted(country_dict.items(), key=lambda x:x[1], reverse=True)
print(sorted_countries)

[('India', 5), ('Bangladesh', 1), ('Qatar', 1), ('Spain', 1), ('Afghanistan', 0), ('Albania', 0), ('Algeria', 0), ('Andorra', 0), ('Angola', 0), ('Antigua & Deps', 0), ('Argentina', 0), ('Armenia', 0), ('Australia', 0), ('Austria', 0), ('Azerbaijan', 0), ('Bahamas', 0), ('Bahrain', 0), ('Barbados', 0), ('Belarus', 0), ('Belgium', 0), ('Belize', 0), ('Benin', 0), ('Bhutan', 0), ('Bolivia', 0), ('Bosnia Herzegovina', 0), ('Botswana', 0), ('Brazil', 0), ('Brunei', 0), ('Bulgaria', 0), ('Burkina', 0), ('Burma', 0), ('Burundi', 0), ('Cambodia', 0), ('Cameroon', 0), ('Canada', 0), ('Cape Verde', 0), ('Central African Rep', 0), ('Chad', 0), ('Chile', 0), ('China', 0), ('Republic of China', 0), ('Colombia', 0), ('Comoros', 0), ('Democratic Republic of the Congo', 0), ('Republic of the Congo', 0), ('Costa Rica', 0), ('Croatia', 0), ('Cuba', 0), ('Cyprus', 0), ('Czech Republic', 0), ('Danzig', 0), ('Denmark', 0), ('Djibouti', 0), ('Dominica', 0), ('Dominican Republic', 0), ('East Timor', 0), ('Ecuador', 0), ('Egypt', 0), ('El Salvador', 0), ('Equatorial Guinea', 0), ('Eritrea', 0), ('Estonia', 0), ('Ethiopia', 0), ('Fiji', 0), ('Finland', 0), ('France', 0), ('Gabon', 0), ('Gaza Strip', 0), ('The Gambia', 0), ('Georgia', 0), ('Germany', 0), ('Ghana', 0), ('Greece', 0), ('Grenada', 0), ('Guatemala', 0), ('Guinea', 0), ('Guinea-Bissau', 0), ('Guyana', 0), ('Haiti', 0), ('Holy Roman Empire', 0), ('Honduras', 0), ('Hungary', 0), ('Iceland', 0), ('Indonesia', 0), ('Iran', 0), ('Iraq', 0), ('Republic of Ireland', 0), ('Israel', 0), ('Italy', 0), ('Ivory Coast', 0), ('Jamaica', 0), ('Japan', 0), ('Jonathanland', 0), ('Jordan', 0), ('Kazakhstan', 0), ('Kenya', 0), ('Kiribati', 0), ('North Korea', 0), ('South Korea', 0), ('Kosovo', 0), ('Kuwait', 0), ('Kyrgyzstan', 0), ('Laos', 0), ('Latvia', 0), ('Lebanon', 0), ('Lesotho', 0), ('Liberia', 0), ('Libya', 0), ('Liechtenstein', 0), ('Lithuania', 0), ('Luxembourg', 0), ('Macedonia', 0), ('Madagascar', 0), ('Malawi', 0), ('Malaysia', 0), ('Maldives', 0), ('Mali', 0), ('Malta', 0), ('Marshall Islands', 0), ('Mauritania', 0), ('Mauritius', 0), ('Mexico', 0), ('Micronesia', 0), ('Moldova', 0), ('Monaco', 0), ('Mongolia', 0), ('Montenegro', 0), ('Morocco', 0), ('Mount Athos', 0), ('Mozambique', 0), ('Namibia', 0), ('Nauru', 0), ('Nepal', 0), ('Newfoundland', 0), ('Netherlands', 0), ('New Zealand', 0), ('Nicaragua', 0), ('Niger', 0), ('Nigeria', 0), ('Norway', 0), ('Oman', 0), ('Ottoman Empire', 0), ('Pakistan', 0), ('Palau', 0), ('Panama', 0), ('Papua New Guinea', 0), ('Paraguay', 0), ('Peru', 0), ('Philippines', 0), ('Poland', 0), ('Portugal', 0), ('Prussia', 0), ('Romania', 0), ('Rome', 0), ('Russian Federation', 0), ('Rwanda', 0), ('St Kitts & Nevis', 0), ('St Lucia', 0), ('Saint Vincent & the Grenadines', 0), ('Samoa', 0), ('San Marino', 0), ('Sao Tome & Principe', 0), ('Saudi Arabia', 0), ('Senegal', 0), ('Serbia', 0), ('Seychelles', 0), ('Sierra Leone', 0), ('Singapore', 0), ('Slovakia', 0), ('Slovenia', 0), ('Solomon Islands', 0), ('Somalia', 0), ('South Africa', 0), ('Sri Lanka', 0), ('Sudan', 0), ('Suriname', 0), ('Swaziland', 0), ('Sweden', 0), ('Switzerland', 0), ('Syria', 0), ('Tajikistan', 0), ('Tanzania', 0), ('Thailand', 0), ('Togo', 0), ('Tonga', 0), ('Trinidad & Tobago', 0), ('Tunisia', 0), ('Turkey', 0), ('Turkmenistan', 0), ('Tuvalu', 0), ('Uganda', 0), ('Ukraine', 0), ('United Arab Emirates', 0), ('United Kingdom', 0), ('United States', 0), ('Uruguay', 0), ('Uzbekistan', 0), ('Vanuatu', 0), ('Vatican City', 0), ('Venezuela', 0), ('Vietnam', 0), ('Yemen', 0), ('Zambia', 0), ('Zimbabwe', 0)]

### Most common places appearing in place field for twitter posts with hashtag #FIFAWorldCup2022

In [12]:
places = {}

for place in full_string:
        if place not in places:
            places.update({place : 1})
        else:
            places[place] = places[place] + 1

sorted_places = sorted(places.items(), key=lambda x:x[1], reverse=True)
print(sorted_places)

[(' المملكة العربية السعودالرياض', 3), ('Timiaouine south الحسيمة いつかは🇰🇷へお嫁へㄱㄱ👰🏻\u200d♀️いつかは🇰🇷へお嫁へㄱㄱ👰🏻\u200d♀️いつかは🇰🇷へお嫁へㄱㄱ👰🏻\u200d♀️Istanbul Buenos AiresУкраинаValencia', 1), (' EspañaMollet del Vallès', 1), (' EspañaUp', 1), (' India IndiaPUNADelhi東京都Mulfand acc#Qatar ماتوفيقي الا باللهTithanHyderabad', 1), (' IndiaRachiEarthKolkata', 1), (' Indiachennai IndiaTokyoLucca', 1), (' Toscana - Tuscany - ItaPatnaBerlin', 1), (' DeutschlandUPFès Médina', 1), (' Royaume du Marocالرياض', 1), (" المملكة العربية السعود대한민국mind somewhere BiharHong KongUkMassachusetts日本🇯🇵\u3000神奈川SpainN 13°48' 0'' / E 100°34' 0''Dhaka", 1), (' BangladeshTokyoNYC', 1)]

In [13]:
# new_search = "#FIFAWorldCup2022"

# tweets = tweepy.Cursor(api.search_tweets,
#                    q=new_search,
#                    ).items(100)

# all_tweets = [tweet.text for tweet in tweets]
# all_tweets[:5]

## Problem 2

In [14]:
api = tweepy.API(auth, wait_on_rate_limit=True)

In [15]:
tweets = tweepy.Cursor(api.get_friends, id = '@AndrewC71614754', include_rts = True, tweet_mode = "extended").items(20)

In [16]:
friends = api.get_friends(user_id='@AndrewC71614754', count=20)
# print(friends)

In [17]:
tweet = friends[0]._json
for key, value in tweet.items():
    print(key)

id
id_str
name
screen_name
location
description
url
entities
protected
followers_count
friends_count
listed_count
created_at
favourites_count
utc_offset
time_zone
geo_enabled
verified
statuses_count
lang
status
contributors_enabled
is_translator
is_translation_enabled
profile_background_color
profile_background_image_url
profile_background_image_url_https
profile_background_tile
profile_image_url
profile_image_url_https
profile_banner_url
profile_link_color
profile_sidebar_border_color
profile_sidebar_fill_color
profile_text_color
profile_use_background_image
has_extended_profile
default_profile
default_profile_image
following
live_following
follow_request_sent
notifications
muting
blocking
blocked_by
translator_type
withheld_in_countries

## A)
### for this section I used the twitter account of an esports player, I had a new account with no followers

In [18]:
tweets_friends = api.get_friends(screen_name='huhi')
tweets_followers = api.get_followers(screen_name='huhi')

columns = ['tweet_id', 'name',  'screen_name', 'location',
            'description', 'followers_count', 'friends_count', 
            'favorites_count', 'creation_time', 'number_of_tweets', 
            'verified', 'follower_followee']
data = []

for tweet in tweets_friends:
    data.append([tweet.id, tweet.name, tweet.screen_name, tweet.location,
                tweet.description, tweet.followers_count, tweet.friends_count, 
                tweet.favourites_count, tweet.created_at, tweet.statuses_count, 
                tweet.verified, 'followee'])
    
for tweet in tweets_followers:
    data.append([tweet.id, tweet.name, tweet.screen_name, tweet.location,
                tweet.description, tweet.followers_count, tweet.friends_count, 
                tweet.favourites_count, tweet.created_at, tweet.statuses_count, 
                tweet.verified, 'follower'])

df = pd.DataFrame(data, columns = columns)

In [19]:
df

,tweet_id,name,screen_name,location,description,followers_count,friends_count,favorites_count,creation_time,number_of_tweets,verified,follower_followee
0,966520621386485760,Young Choi 영호,youngmidlol,LA,Professional League of Legends Player for @gol...,871,249,117,2018-02-22 03:50:48+00:00,20,False,followee
1,1377830581384318976,tina :T,tinakittenalt,she/her,carrot girl! 🥕 the main: @tinakitten\npfp! @pr...,467151,14,77,2021-04-02 03:52:52+00:00,703,False,followee
2,4445212467,Licorice,Licorice,,"Top Laner for @GoldenGuardians, Undefeated MSI...",63025,422,5841,2015-12-11 05:42:46+00:00,1433,True,followee
3,928328069596692480,Golden Guardians,GoldenGuardians,,Official Account of the Golden Guardians - Lea...,53166,157,8870,2017-11-08 18:27:14+00:00,6901,True,followee
4,637385264,Hunter Leigh,HunterLeigh,"San Francisco, CA",Head of Esports for @warriors and @goldenguard...,3396,131,7404,2012-07-16 23:48:02+00:00,345,False,followee
5,1344146441766256642,Hipyo,HipyoTech,Washington,"Seattle, WA based Tech Content Creator\nI make...",28322,765,2517,2020-12-30 05:01:08+00:00,1994,False,followee
6,58589634,colinyoungwolff,colinyoungwolff,all tweets are my own,Los Angeles photographer (https://t.co/H7QWHBM...,4439,1873,5863,2009-07-20 21:02:32+00:00,1122,False,followee
7,793473756094164992,Toucouille,Toucouille_lol,"Paris, France",Professional League of Legends player for @Tea...,41738,769,3272,2016-11-01 15:24:20+00:00,3035,True,followee
8,314490067,kenzi,kenzi131,"seoul, korea",korea media dailyesports reporter and photogra...,57532,2022,2380,2011-06-10 10:29:26+00:00,82828,True,followee
9,754006735468261376,i am reading all that,LilNasX,Barcelona,👎🏾,8028996,723,42713,2016-07-15 17:36:29+00:00,12719,True,followee
10,3862673773,yougelly 💕,yougellyy,hidden leaf village,"hi, my name is sally and i like games! ♡\nstre...",34268,621,15506,2015-10-11 21:35:06+00:00,4598,False,followee
11,935906156773629952,hasan,KaoriLoL,,21yo ad player for @KarmineCorp Business Inqui...,19179,389,1782,2017-11-29 16:19:50+00:00,186,True,followee
12,1293735157258579969,triciaisabirdy,triciaisabirdy,"Los Angeles, CA",Pro Chef Twitch ambassador || Bi || she/her ||...,72610,679,15821,2020-08-13 02:24:39+00:00,4884,True,followee
13,3180766950,jpak,itsjpak_,"Los Angeles, CA",part of the @Twitch partnered fam 💜 prev: 100T...,4348,225,3631,2015-04-30 16:29:10+00:00,1462,False,followee
14,423570545,Becca,BeccaTILTS,"Los Angeles, CA",i play games / Business Email: beccaTILTS@gmai...,79492,858,17770,2011-11-28 17:33:09+00:00,13424,True,followee
15,2872493989,KELLY WAKASA,KellyWakasa,"California, USA",do what excites youTUBE - kelly wakasa,13799,34,719,2014-10-23 02:39:40+00:00,728,False,followee
16,3929142139,100T JhbTeam,JhbTeam,"Los Angeles, CA",20 - Employee for @100Thieves & Host of TBH w/...,225355,1449,67297,2015-10-17 21:48:53+00:00,69785,False,followee
17,1007278919551148034,River,lolRiver,,I'm River play for @GoldenGuardians Agency : @...,2954,71,173,2018-06-14 15:09:43+00:00,77,True,followee
18,2795145212,Gabby Durden,LeTigress,"Los Angeles, CA",play-by-play caster & host | #LCS | big #VCT &...,18175,795,22739,2014-09-07 02:11:40+00:00,13167,True,followee
19,1462144869233614854,Min-cheol Kim,C9Berserker,Los Angeles,Professional League of Legends ADC for @Cloud...,33949,171,101,2021-11-20 19:45:27+00:00,145,True,followee
20,1345023320366993409,trixx,heytrixxie,"London, United Kingdom",I play games online sometimes... ▫️https://t.c...,4845,665,20511,2021-01-01 15:05:31+00:00,10480,False,follower
21,1620164051622928384,Sam,Quacsimile,,,0,163,4,2023-01-30 20:57:07+00:00,0,False,follower
22,1446573829631971335,DB,DietBlvck,,"F/A LFAW, I play video games when I’m bored. T...",21,100,703,2021-10-08 20:31:00+00:00,89,False,follower
23,1528465146053419008,Koga,lostkoga,CA,FIGHT OR BE FORGOTTEN,0,126,250,2022-05-22 19:57:59+00:00,36,False,follower
24,1164972646997483520,복자,lol_bokja,,덕질과 혼잣말하는 계정,6,132,0,2019-08-23 18:48:27+00:00,1,False,follower
25,4839801375,Brandon Feaver,BrandonFeaver,"New Brunswick, Canada",Amateur disc golfer for Coastal Disc Golf. 1x🏆...,178,269,3428,2016-01-23 21:27:19+00:00,1845,False,follower
26,1467249182889156612,NA Challengers,NAChallengers,,A bot that posts when an NA League of Legends ...,1124,379,0,2021-12-04 21:48:15+00:00,1690,False,follower
27,1130292660076503041,Corey,ChristianCore19,"Webster, TX",I'm just a random nerd,11,149,50,2019-05-20 02:02:24+00:00,31,False,follower
28,1611272008788246528,Alex,Varulv__,,Pokémon • Avid Gamer • Nintendo Switch • Plays...,20,279,711,2023-01-06 08:02:48+00:00,172,False,follower
29,1473964831560585226,Kasno,to_lacerate,in the zone,"there are no angels nor demons , there are onl...",2428,2910,14935,2021-12-23 10:33:11+00:00,7609,False,follower
30,966520621386485760,Young Choi 영호,youngmidlol,LA,Professional League of Legends Player for @gol...,871,249,117,2018-02-22 03:50:48+00:00,20,False,follower
31,979635799,Sweet,SugaDaddySweet,,,407,1433,42762,2012-11-30 03:00:17+00:00,2917,False,follower
32,772765245999869952,Zuhet,Zuhet_,Danmark,Just your regular\nKrolf playing • eSport watc...,21,342,3595,2016-09-05 11:56:06+00:00,68,False,follower
33,1534296753788399616,tw1lly,tw1lly__,,,8,98,0,2022-06-07 22:10:36+00:00,1,False,follower
34,1617896959443963904,Gaming Roomz,gamingroomz,,An inspiring collection of gaming rooms from G...,5,80,26,2023-01-24 14:48:03+00:00,29,False,follower
35,4861304057,Michael Brackett,ThePandaMayne,,,20,114,1715,2016-01-29 19:38:17+00:00,14,False,follower
36,609601504,Matt Hart,Mafro37,"Colorado, USA",,413,676,36984,2012-06-16 01:51:00+00:00,2052,False,follower
37,1284587988119363586,Sheriff,itsdrsheriff,behind you,Founder of @FlowerpotProdu | https://t.co/rDcJ...,73,2846,4766,2020-07-18 20:37:16+00:00,7582,False,follower
38,1617585367187587088,kl0wn420,kl0wn420,,,12,239,368,2023-01-23 18:09:57+00:00,0,False,follower
39,1471226489240702979,Lasse,lassexyz9,NEOM,very well known famous socialite of great cele...,105,283,18689,2021-12-15 21:11:51+00:00,63,False,follower

## B)

In [20]:
df.groupby('follower_followee')[['friends_count', 'followers_count']].mean()

                   friends_count  followers_count
follower_followee
followee                  620.85        462638.25
follower                  576.60           528.40

### I average followers of followers = 287.55
### II average followers of followees = 462848.15
### III average followees of followers = 609.70
### IV average followees of followees = 620.55

In [21]:
df.groupby('follower_followee')[['verified']].count()

                   verified
follower_followee
followee                 20
follower                 20

### V Number of verified: Followers = 20, Followees = 20, Total = 40

In [22]:
df.groupby('follower_followee')[['favorites_count']].mean()

                   favorites_count
follower_followee
followee                  11229.65
follower                   7480.70

In [23]:
df.favorites_count.mean()

9355.175

### VI average favorites: Followers = 6429.50, Followees = 11230.05, combined = 8829.775

In [24]:
df.groupby('follower_followee')[['number_of_tweets']].mean()

                   number_of_tweets
follower_followee
followee                   10977.80
follower                    1734.95

In [25]:
df.number_of_tweets.mean()

6356.375

### VII average number of tweets:  Followers = 1198.25, Followees = 10972.10, combined = 6085.175

In [26]:
df["year"] = df["creation_time"].dt.year

In [27]:
df.head()

,tweet_id,name,screen_name,location,description,followers_count,friends_count,favorites_count,creation_time,number_of_tweets,verified,follower_followee,year
0,966520621386485760,Young Choi 영호,youngmidlol,LA,Professional League of Legends Player for @gol...,871,249,117,2018-02-22 03:50:48+00:00,20,False,followee,2018
1,1377830581384318976,tina :T,tinakittenalt,she/her,carrot girl! 🥕 the main: @tinakitten\npfp! @pr...,467151,14,77,2021-04-02 03:52:52+00:00,703,False,followee,2021
2,4445212467,Licorice,Licorice,,"Top Laner for @GoldenGuardians, Undefeated MSI...",63025,422,5841,2015-12-11 05:42:46+00:00,1433,True,followee,2015
3,928328069596692480,Golden Guardians,GoldenGuardians,,Official Account of the Golden Guardians - Lea...,53166,157,8870,2017-11-08 18:27:14+00:00,6901,True,followee,2017
4,637385264,Hunter Leigh,HunterLeigh,"San Francisco, CA",Head of Esports for @warriors and @goldenguard...,3396,131,7404,2012-07-16 23:48:02+00:00,345,False,followee,2012

In [28]:
df2 = df[df['follower_followee'] == 'follower']
df2.groupby('year')[['follower_followee']].count()

      follower_followee
year
2012                  2
2016                  3
2018                  1
2019                  2
2020                  1
2021                  5
2022                  2
2023                  4

## VIII

### (Above) Follower by year

In [29]:
df3 = df[df['follower_followee'] == 'followee']
df3.groupby('year')[['follower_followee']].count()

      follower_followee
year
2009                  1
2011                  2
2012                  1
2014                  2
2015                  4
2016                  2
2017                  2
2018                  2
2020                  2
2021                  2

### (Above) Followee by year

# Problem 3

In [30]:
ny_favorites = api.get_friends(screen_name='The New York Times', count=100)

with open("nytimes-favorites.json", 'w') as file:
    for tweet in ny_favorites:
        file.write(json.dumps(tweet._json, indent = 4))

# Problem 4

In [31]:
import requests
page = requests.get("https://cs.usu.edu/people/HamidKarimi/projects.html")

In [32]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(page.content, 'html.parser')

In [33]:
# print(soup.prettify())

In [34]:
# for title in soup.findAll('b'):
#     print (title)

In [35]:
# for description in soup.findAll('p'):
#     print (description)

In [36]:
titles=[]
descriptions=[]
for title in soup.findAll('b'):
    titles.append(title)
for description in soup.findAll('p'):
    descriptions.append(description)

In [37]:
def merge(list1, list2):
     
    merged_list = tuple(zip(list1, list2))
    return merged_list

In [38]:
results = merge(titles, descriptions)
print(results)

((<b>Social Media Mining</b>, <p style="font-size:18px">  Online social media has become an integral part of human life in the 21st century. The number of social media users in 2020 was estimated to be around 3.6 billion individuals. Social media platforms (e.g., Facebook, Twitter, Pinterest, Youtube) have facilitated interpersonal communication, diffusion of information, the creation of groups and communities, boosting large and small businesses, to name a few. Moreover, online social media users produce an enormous amount of information (high volume), at the fast speed (high velocity), and in different formats, e.g., text, audio, video, graph (wide variety). These three Vs are the principal characteristics of Big Data. Social Media Mining is the process of representing, analyzing, and extracting meaningful patterns from the Big Data generated from social media platforms.  In this project, we study social media mining from multiple aspects, e.g., trying to make sense of the user-generated content (mostly text), investigating the friendship patterns, applying and revising social theories, etc. <br/> <br/> Relevant papers: <a href="https://dl.acm.org/doi/10.1145/3465336.3475115"> [1] </a> <a href="https://dl.acm.org/doi/10.1145/3459637.3482418"> [2] </a> <a href="https://doi.org/10.1145/3341161.3342884"> [3] </a> <a href="https://www.tcrecord.org/Content.asp?ContentId=23045"> [4] </a> </p>), (<b>Teachers in Social Media</b>, <p style="font-size:18px">
									Online social media has transformed and connected traditional social networks within the schoolhouse to a broader and expanded world outside. Thanks to advancements in communication, educators have access to ample online instructional resources curated and shared across social media platforms. In such an expanded virtual space, teachers engage in various activities within their community, e.g., exchanging instructional resources, seeking new teaching methods, and engaging in online discussions. There are several important reasons why we should care about teachers in social media:
									1) Teaching as a career is no longer confined to the physical world, and its development has a huge presence in online social media.
									2) Social media is a reliable support group for teachers and aids in the widespread diffusion of educational resources used in various classroom activities. 3) The social media data offers several significant benefits compared to traditional data for studying teachers (i.e., interviews or surveys), e.g., no proxy in tapping into teaching practices and their thinking, real-time access, no response bias, availability of data in a wide variety of formats, etc.
									As a specific application of Social Media Mining, in the Teachers in Social Media project, we devise novel and efficient data mining and machine learning algorithms to understand how and why teachers utilize online social media for pedagogical purposes.
									<br/> <br/> Relevant papers:  <a href="https://ieeexplore.ieee.org/document/9671476"> [1] </a> <a href="https://www.journals.uchicago.edu/doi/full/10.1086/715482">[2] </a> <a href="https://ieeexplore.ieee.org/abstract/document/9368377"> [3] </a> <a href="https://dl.acm.org/doi/10.1145/3386527.3405941">[4] </a> <a href="https://link.springer.com/chapter/10.1007/978-3-030-52240-7_24">[5] </a> </p>), (<b>Learning Analytics</b>, <p style="font-size:18px"><a href="https://en.wikipedia.org/wiki/Learning_analytics">Learning analytics </a> is the measurement, collection, analysis, and reporting of data about learners and their contexts, for purposes of understanding and optimizing learning and the environments in which it occurs. In this project, we are mostly interested in understanding students' behavior and their acadmic performance by studying their click footprints (keystrokes) while interacting with a learning environment. Essentially, we develop analytic tools and machine learning algorithms to find meaningful patterns in the keystrokes e.g., best coding practices. <br/> <br/> Relevant papers:  <a href="https://educationaldatamining.org/files/conferences/EDM2020/papers/paper_45.pdf"> [1] </a> <a href="http://www.cse.msu.edu/~wangzh65/AI4EDU/papers/19.pdf"> [2] </a> </p>), (<b> Misinformation and Information Credibility</b>, <p style="font-size:18px">Despite the tremendous positive technological and societal transformations brought about by big data, it causes a significant challenge: online misinformation.<a href="https://en.wikipedia.org/wiki/Misinformation"> Misinformation </a> is incorrect or misleading information unintentionally presented as fact. Online social media platforms (notably Facebook and Twitter) are the major sources of disseminating misinformation.   Misinformation on social media spreads quickly compared to traditional media because of the lack of regulation and examination required before posting. Meanwhile, social media users are highly connected and information can propagate quickly and easily reach a massive amount of users. (Online) misinformation has been identified as a global threat and has major short-term and long-term social, political, economic, and even health-related consequences. Addressing the information credibility problem becomes increasingly important and necessary to provide healthy, trustworthy and reliable online worlds. In this project, we examine misinformation from macro and micro perspectives and develop efficient algorithms and systems to detect and intervene misinformation.	     <br/> Relevant papers: <a href="https://aclanthology.org/C18-1131.pdf">[1] </a> <a href="https://aclanthology.org/N19-1347.pdf"> [2]</a> <a href="https://ieeexplore.ieee.org/abstract/document/8508296"> [3]</a> <a href="https://ieeexplore.ieee.org/abstract/document/8508654"> [4] </a> <a href="https://ieeexplore.ieee.org/abstract/document/8621909"> [5] </a> </p>), (<b>Fairness in Machine Learning and AI</b>, <p><p style="font-size:18px">The elimination of discrimination is an important issue that our modern-day society is facing. Learning from human behaviors, AI systems have been shown to inherit the prejudices from humans. Since such AI systems have been integrated in many human-related applications, it is important to ensure that they do not make biased decisions against a particular group of people or individuals. In this research direction, we work on detecting bias in machine learning model as well as developing fair algorithms. Our approaches are applicable to various domains, such as natural language processing, recommender systems and education. <br/> <br/> Relevant papers: <a href="https://aclanthology.org/2021.findings-acl.7">[1] </a></p>
<!--a href="project.html" class="button">Learn more</a-->
</p>))